version: "2"
services:
  db:
    image: mysql
    hostname: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: dbname
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./db/updates:/docker-entrypoint-initdb.d
      - persistent:/var/lib/mysql
    networks:
      - default
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - 8000:80
    environment:
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    networks:
      - default
  server-api:
    build:
      context: ./
      dockerfile: server-release.Dockerfile
    container_name: server-api
    restart: always
    links:
      - db:db
    env_file:
      - server/dev.env
    volumes:
      - "./server:/app"
    ports:
      - "8080:8080"
    networks:
      - default
volumes:
  persistent: